name: packscan_mobile
description: "PackScan Field Officer App for Legal Metrology Verification (Department of Consumer Affairs)"
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  http: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
