"""Initial schema with sequences

Revision ID: 9b28577db6cd
Revises: 
Create Date: 2026-09-10 21:13:36.458714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b28577db6cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.CreateSequence(sa.Sequence('inspection_seq')))
    op.add_column('extracted_fields', sa.Column('bbox_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('extracted_fields', sa.Column('rule_min_mm', sa.Float(), nullable=True))
    op.drop_column('extracted_fields', 'bbox')
    op.add_column('inspections', sa.Column('inspection_code', sa.String(length=50), nullable=False))
    op.add_column('inspections', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('inspections', sa.Column('overall_severity', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_inspections_inspection_code'), 'inspections', ['inspection_code'], unique=True)
    op.add_column('products', sa.Column('manufacturer', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'manufacturer')
    op.drop_index(op.f('ix_inspections_inspection_code'), table_name='inspections')
    op.drop_column('inspections', 'overall_severity')
    op.drop_column('inspections', 'completed_at')
    op.drop_column('inspections', 'inspection_code')
    op.add_column('extracted_fields', sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('extracted_fields', 'rule_min_mm')
    op.drop_column('extracted_fields', 'bbox_json')
    op.execute(sa.schema.DropSequence(sa.Sequence('inspection_seq')))
    # ### end Alembic commands ###
